In [1]:

import numpy as np
import matplotlib.pyplot as plt


# Punto 2

In [2]:
# Definición de la Clase Sistema Lineal

class SistemaLineal:
    
    def __init__(self, M,b):
        
        self.M = M
        self.b = b
        
    def Metodo_Jacobi(self, itmax=1000, error=1e-10):
        
        rows,col = M.shape
        it = 0
        
        solution = np.zeros(col)
        
        sumatoria = np.zeros_like(solution)
        
        res = np.linalg.norm(b - np.dot(M,solution))
        
        while res > error and it < itmax:
            
            for i in range(rows):
                
                sum_ = 0
                
                for j in range(col):
                    
                    if i != j:
                        sum_ += M[i][j]*solution[j]
                        
                sumatoria[i] = sum_
                
            for k in range(rows):
                
                if M[k][k] != 0:
                    
                    solution[k] = (b[k] - sumatoria[k])/M[k][k]
                    
                else:
                    print('No se puede solucionar con el método de Jacobi')
                    
            res = np.linalg.norm( b - np.dot(M,solution) )
            
            it += 1
        
        return solution,it
    
    
    def Metodo_Gauss_Seidel(self, itmax=1000, error=1e-10):
        
        rows,col = M.shape
        it = 0
        
        solution = np.zeros(col)
        
        res = np.linalg.norm(b - np.dot(M,solution))
        
        while res > error and it < itmax:
            
            for i in range(rows):
                
                sum_ = 0
                
                for j in range(col):
                    
                    if i != j:
                        sum_ += M[i][j]*solution[j]
                        
                solution[i] = (b[i] - sum_)/M[i][i] 
                
            res = np.linalg.norm( b - np.dot(M,solution) )
            
            it += 1
        
        return solution,it

In [3]:
# Matriz (Sistema de ecuaciones)

M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)


[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


### Método de Jacobi

In [4]:

jacobi_ans = SistemaLineal(M,b)
Respuesta1 = jacobi_ans.Metodo_Jacobi()[0]
Iteraciones1 = jacobi_ans.Metodo_Jacobi()[1]

print(f'Solución al sistema de ecuaciones usando el método de Jacobi: {Respuesta1}')
print(f'Iteraciones realizadas: {Iteraciones1}')



Solución al sistema de ecuaciones usando el método de Jacobi: [1. 1. 1.]
Iteraciones realizadas: 23


### Método de Gauss-Seidel

In [5]:

gauss_sidel_ans = SistemaLineal(M,b)
Respuesta2 = gauss_sidel_ans.Metodo_Gauss_Seidel()[0]
Iteraciones2 = gauss_sidel_ans.Metodo_Gauss_Seidel()[1]

print(f'Solución al sistema de ecuaciones usando el método de Gauss-Seidel: {Respuesta2}')
print(f'Iteraciones realizadas: {Iteraciones2}')


Solución al sistema de ecuaciones usando el método de Gauss-Seidel: [1. 1. 1.]
Iteraciones realizadas: 18
