In [1]:

import numpy as np
import matplotlib.pyplot as plt


# Punto 3

$$ AB = \begin{pmatrix}1 & 0 & 0 \\ 5 & 1 & 0 \\-2 & 3 & 1 \\\end{pmatrix} \cdot \begin{pmatrix} 4 & -2 & 1\\ 0 & 3 & 7\\ 0&0&2\\ \end{pmatrix} = \begin{pmatrix}4&-2&1\\ 20&-7&12\\-8&13&21\\ \end{pmatrix} $$
$$ AB = \begin{pmatrix}4&-2&1\\ 20&-7&12\\-8&13&21\\ \end{pmatrix}$$

In [2]:
# Definición de la función para multiplicar dos matrices

def Obtener_multiplicacion_matrices(M1,M2):
    
    colM1 = len(M1[0])
    rowsM1 = len(M1)
    colM2 = len(M2[0])
    rowsM2 = len(M2)
    
    if colM1 != rowsM2:
        print('No se pueden multiplicar')
        return None
    
    solution = np.zeros((rowsM1,colM2))
    
    for i in range(rowsM1):      
        
        for j in range(colM2):
            
            sum_ = 0
            for a in range(rowsM1):
                
                sum_ += M1[i][a]*M2[a][j]
                
            solution[i][j] = sum_
            
    return solution


In [3]:
# Definición de las matrices

A = np.array(([1,0,0],[5,1,0],[-2,3,1]))
B = np.array(([4,-2,1],[0,3,7],[0,0,2]))

print(A)
print(B)


[[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]
[[ 4 -2  1]
 [ 0  3  7]
 [ 0  0  2]]


In [4]:

respuesta = Obtener_multiplicacion_matrices(A,B)

print(respuesta)


[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


$$ AB = \begin{pmatrix}4&-2&1\\ 20&-7&12\\-8&13&21\\ \end{pmatrix}$$