In [1]:

import numpy as np
import matplotlib.pyplot as plt


## Punto 1

In [2]:
# Sistema de ecuaciones 

M = np.array([[3,-1,-1],[-1.,3.,1.],[2,1,4]])
print(M)
b = np.array([1.,3.,7.])
print(b)


[[ 3. -1. -1.]
 [-1.  3.  1.]
 [ 2.  1.  4.]]
[1. 3. 7.]


In [3]:
# Definición de la función

def Metodo_Gauss_Seidel(M,b, itmax=1000, error=1e-10):
    
    rows,col = M.shape
    it = 0
        
    solution = np.zeros(col)
        
    res = np.linalg.norm(b - np.dot(M,solution))
        
    while res > error and it < itmax:
            
        for i in range(rows):
                
            sum_ = 0
                
            for j in range(col):
                    
                if i != j:
                    sum_ += M[i][j]*solution[j]
                        
            solution[i] = (b[i] - sum_)/M[i][i] 
                
              
        res = np.linalg.norm( b - np.dot(M,solution) )
            
        it += 1

    return solution,it
    

In [4]:

respuesta,iteraciones = Metodo_Gauss_Seidel(M,b)

print(f'La solución al sistema de ecuaciones es: {respuesta}')
print(f'Iteraciones necesarias: {iteraciones}')


La solución al sistema de ecuaciones es: [1. 1. 1.]
Iteraciones necesarias: 18
